[
build
]
  publish = "."
  functions = "netlify/functions"
  command = "cd netlify/functions && npm install && cd ../.."

[
dev
]
  framework = "#static"

[[
redirects
]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[
plugins
]]
  package = "@netlify/plugin-functions-install-core"